import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ComputedWeeklyRecord } from './calculations';
import { MockFlock, getStoredFlockRecords } from './mockData';

/**
 * Generates and downloads a printable PDF report for a single flock
 */
export function exportSingleFlockPDF(flock: MockFlock, records: ComputedWeeklyRecord[]) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });

  // 1. Report Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 842, 60, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('RBCL FLOCK MONITOR - UNIT-B BREEDER FARM', 40, 36);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(52, 211, 153); // emerald-400
  doc.text('WEEKLY GROWING PERFORMANCE REPORT', 40, 50);

  // 2. Metadata Block
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Flock No: ${flock.flockNo}`, 40, 85);
  doc.text(`Shed: ${flock.shedNo}`, 160, 85);
  doc.text(`Breed: ${flock.breed}`, 260, 85);
  doc.text(`Unit: ${flock.unit}`, 360, 85);
  doc.text(`Housing Date: ${flock.housingDate}`, 460, 85);

  const latest = records[records.length - 1];
  if (latest) {
    doc.text(`Current Age: Week ${latest.ageWeeks}`, 620, 85);
  }

  // 3. Weekly Data Table
  const tableData = records.map((r) => [
    `Wk ${r.ageWeeks}`,
    String(r.weekEndDate),
    r.housedF.toLocaleString(),
    r.mortalityF.toLocaleString(),
    r.soldF.toLocaleString(),
    r.display.weeklyDepletionPctF,
    r.display.cumulativeDepletionPctF,
    r.stdWeightF ? `${r.stdWeightF}g` : '—',
    r.actualWeightF ? `${r.actualWeightF}g` : '—',
    r.display.weightDeviationGF ? `${r.display.weightDeviationGF}g` : '—',
    r.housedM.toLocaleString(),
    r.mortalityM.toLocaleString(),
    r.display.weeklyDepletionPctM,
    r.display.cumulativeDepletionPctM,
    r.actualWeightM ? `${r.actualWeightM}g` : '—',
  ]);

  autoTable(doc, {
    startY: 105,
    head: [
      [
        'Age',
        'Date End',
        'Housed F',
        'Mort F',
        'Sold F',
        'Dep F %',
        'Cum Dep F %',
        'Std Wt F',
        'Act Wt F',
        'Dev F',
        'Housed M',
        'Mort M',
        'Dep M %',
        'Cum Dep M %',
        'Act Wt M',
      ],
    ],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { halign: 'center', fontStyle: 'bold' },
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right', fontStyle: 'bold' },
      6: { halign: 'right', fontStyle: 'bold' },
      7: { halign: 'right' },
      8: { halign: 'right' },
      9: { halign: 'right' },
      10: { halign: 'right' },
      11: { halign: 'right' },
      12: { halign: 'right' },
      13: { halign: 'right' },
      14: { halign: 'right' },
    },
    foot: [
      [
        'Summary',
        `${records.length} Weeks`,
        latest ? latest.liveAtWeekEndF.toLocaleString() : '',
        records.reduce((sum, r) => sum + r.mortalityF, 0).toLocaleString(),
        records.reduce((sum, r) => sum + r.soldF, 0).toLocaleString(),
        '—',
        latest ? latest.display.cumulativeDepletionPctF : '',
        '—',
        latest?.actualWeightF ? `${latest.actualWeightF}g` : '',
        latest ? latest.display.weightDeviationGF : '',
        latest ? latest.liveAtWeekEndM.toLocaleString() : '',
        records.reduce((sum, r) => sum + r.mortalityM, 0).toLocaleString(),
        '—',
        latest ? latest.display.cumulativeDepletionPctM : '',
        latest?.actualWeightM ? `${latest.actualWeightM}g` : '',
      ],
    ],
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      fontSize: 8,
    },
  });

  // Footer page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by RBCL Flock Monitor · Page ${i} of ${pageCount}`,
      40,
      doc.internal.pageSize.height - 20
    );
  }

  doc.save(`RBCL_Flock_${flock.flockNo}_Report.pdf`);
}
